version: "3"

tasks:
  redis:start:
    desc: Start Redis server
    cmds:
      - docker-compose up redis -d
      - docker-compose up redis-insight -d

  install-deps:
    desc: Install all deps
    cmds:
      - uv run patchright install chromium

  celery:worker:
    desc: Start Celery worker
    cmds:
      - uv run celery -A scraper.tasks worker --loglevel=debug --concurrency=5 --pool=threads

  celery:flower:
    desc: Start Flower monitoring tool
    cmds:
      - uv run celery -A scraper.tasks flower --port=5555

  scrape:simple:
    desc: Run the simple example scraper
    cmds:
      - uv run python examples/simple_example.py

  scrape:browser:
    desc: Run the browser example scraper
    cmds:
      - uv run browser

  scrape:docker:
    desc: Run the scraper in docker
    cmds:
      - docker compose up
